name: Generate Index Min

on:
  push:
    paths:
      - index.json

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Install jq
      run: sudo apt-get install jq

    - name: Generate index.min.json
      run: jq -c 'map(select(.nsfw != 1))' index.json > index.min.json

    - name: Commit changes
      run: |
        git config --global user.name 'TheLordofD'
        git config --global user.email '161926281+TheLordofD@users.noreply.github.com'
        git add .
        git commit -m "Update index.min.json"
        git push
